/*
 * Copyright (C) 2012 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.manish.customgridview.displayingbitmaps.provider;

public class Images {

    public final static String[] imageUrls = new String[] {
            "http://www.stu.ru/images/theme/29805.jpg",
            "http://www.stu.ru/images/theme/29807.jpg",
            "http://www.stu.ru/images/theme/29809.jpg",
            "http://www.stu.ru/images/theme/29811.jpg",
            "http://www.stu.ru/images/theme/29813.jpg",
            "http://www.stu.ru/images/theme/29815.jpg",
            "http://www.stu.ru/images/theme/29817.jpg",
            "http://www.stu.ru/images/theme/29819.jpg",
            "http://www.stu.ru/images/theme/29821.jpg",
            "http://www.stu.ru/images/theme/29823.jpg",
            "http://www.stu.ru/images/theme/29825.jpg",
            "http://www.stu.ru/images/theme/29827.jpg",
            "http://www.stu.ru/images/theme/29829.jpg",
            "http://www.stu.ru/images/theme/29831.jpg",
            "http://www.stu.ru/images/theme/29833.jpg",
            "http://www.stu.ru/images/theme/29835.jpg",
            "http://www.stu.ru/images/theme/29837.jpg",
            "http://www.stu.ru/images/theme/29839.jpg",
            "http://www.stu.ru/images/theme/29841.jpg",
            "http://www.stu.ru/images/theme/29843.jpg",
            "http://www.stu.ru/images/theme/29845.jpg",
            "http://www.stu.ru/images/theme/29847.jpg",
            "http://www.stu.ru/images/theme/29849.jpg",
            "http://www.stu.ru/images/theme/29851.jpg",
            "http://www.stu.ru/images/theme/29853.jpg",
            "http://www.stu.ru/images/theme/29855.jpg",
            "http://www.stu.ru/images/theme/29857.jpg",
            "http://www.stu.ru/images/theme/29859.jpg",
            "http://www.stu.ru/images/theme/29861.jpg",
            "http://www.stu.ru/images/theme/29863.jpg",
            "http://www.stu.ru/images/theme/29865.jpg",
            "http://www.stu.ru/images/theme/29867.jpg",
            "http://www.stu.ru/images/theme/29869.jpg",
            "http://www.stu.ru/images/theme/29871.jpg",
            "http://www.stu.ru/images/theme/29873.jpg",
            "http://www.stu.ru/images/theme/29875.jpg",
            "http://www.stu.ru/images/theme/29877.jpg",
            "http://www.stu.ru/images/theme/29879.jpg",
            "http://www.stu.ru/images/theme/29881.jpg",
            "http://www.stu.ru/images/theme/29883.jpg",
            "http://www.stu.ru/images/theme/29885.jpg",
            "http://www.stu.ru/images/theme/29887.jpg",
            "http://www.stu.ru/images/theme/29889.jpg",

            "http://www.stu.ru/images/theme/29761.jpg",
            "http://www.stu.ru/images/theme/29763.jpg",
            "http://www.stu.ru/images/theme/29765.jpg",
            "http://www.stu.ru/images/theme/29767.jpg",
            "http://www.stu.ru/images/theme/29769.jpg",
            "http://www.stu.ru/images/theme/29771.jpg",
            "http://www.stu.ru/images/theme/29773.jpg",
            "http://www.stu.ru/images/theme/29775.jpg",
            "http://www.stu.ru/images/theme/29777.jpg",
            "http://www.stu.ru/images/theme/29779.jpg",
            "http://www.stu.ru/images/theme/29781.jpg",
            "http://www.stu.ru/images/theme/29783.jpg",
            "http://www.stu.ru/images/theme/29785.jpg",
            "http://www.stu.ru/images/theme/29787.jpg",
            "http://www.stu.ru/images/theme/29789.jpg",
            "http://www.stu.ru/images/theme/29791.jpg",
            "http://www.stu.ru/images/theme/29793.jpg",
            "http://www.stu.ru/images/theme/29795.jpg",
            "http://www.stu.ru/images/theme/29797.jpg",
            "http://www.stu.ru/images/theme/29799.jpg",
            "http://www.stu.ru/images/theme/29801.jpg",
            "http://www.stu.ru/images/theme/29803.jpg",

            "http://www.stu.ru/images/theme/29566.jpg",
            "http://www.stu.ru/images/theme/29568.jpg",
            "http://www.stu.ru/images/theme/29570.jpg",
            "http://www.stu.ru/images/theme/29572.jpg",
            "http://www.stu.ru/images/theme/29574.jpg",
            "http://www.stu.ru/images/theme/29576.jpg",
            "http://www.stu.ru/images/theme/29578.jpg",
            "http://www.stu.ru/images/theme/29580.jpg",
            "http://www.stu.ru/images/theme/29582.jpg",
            "http://www.stu.ru/images/theme/29584.jpg",
            "http://www.stu.ru/images/theme/29586.jpg",

    };

    public final static String[] imageThumbUrls = new String[] {
            "http://www.stu.ru/images/theme/29804.jpg",
            "http://www.stu.ru/images/theme/29806.jpg",
            "http://www.stu.ru/images/theme/29808.jpg",
            "http://www.stu.ru/images/theme/29810.jpg",
            "http://www.stu.ru/images/theme/29812.jpg",
            "http://www.stu.ru/images/theme/29814.jpg",
            "http://www.stu.ru/images/theme/29816.jpg",
            "http://www.stu.ru/images/theme/29818.jpg",
            "http://www.stu.ru/images/theme/29820.jpg",
            "http://www.stu.ru/images/theme/29822.jpg",
            "http://www.stu.ru/images/theme/29824.jpg",
            "http://www.stu.ru/images/theme/29826.jpg",
            "http://www.stu.ru/images/theme/29828.jpg",
            "http://www.stu.ru/images/theme/29830.jpg",
            "http://www.stu.ru/images/theme/29832.jpg",
            "http://www.stu.ru/images/theme/29834.jpg",
            "http://www.stu.ru/images/theme/29836.jpg",
            "http://www.stu.ru/images/theme/29838.jpg",
            "http://www.stu.ru/images/theme/29840.jpg",
            "http://www.stu.ru/images/theme/29842.jpg",
            "http://www.stu.ru/images/theme/29844.jpg",
            "http://www.stu.ru/images/theme/29846.jpg",
            "http://www.stu.ru/images/theme/29848.jpg",
            "http://www.stu.ru/images/theme/29850.jpg",
            "http://www.stu.ru/images/theme/29852.jpg",
            "http://www.stu.ru/images/theme/29854.jpg",
            "http://www.stu.ru/images/theme/29856.jpg",
            "http://www.stu.ru/images/theme/29858.jpg",
            "http://www.stu.ru/images/theme/29860.jpg",
            "http://www.stu.ru/images/theme/29862.jpg",
            "http://www.stu.ru/images/theme/29864.jpg",
            "http://www.stu.ru/images/theme/29866.jpg",
            "http://www.stu.ru/images/theme/29868.jpg",
            "http://www.stu.ru/images/theme/29870.jpg",
            "http://www.stu.ru/images/theme/29872.jpg",
            "http://www.stu.ru/images/theme/29874.jpg",
            "http://www.stu.ru/images/theme/29876.jpg",
            "http://www.stu.ru/images/theme/29878.jpg",
            "http://www.stu.ru/images/theme/29880.jpg",
            "http://www.stu.ru/images/theme/29882.jpg",
            "http://www.stu.ru/images/theme/29884.jpg",
            "http://www.stu.ru/images/theme/29886.jpg",
            "http://www.stu.ru/images/theme/29888.jpg",

            "http://www.stu.ru/images/theme/29760.jpg",
            "http://www.stu.ru/images/theme/29762.jpg",
            "http://www.stu.ru/images/theme/29764.jpg",
            "http://www.stu.ru/images/theme/29766.jpg",
            "http://www.stu.ru/images/theme/29768.jpg",
            "http://www.stu.ru/images/theme/29770.jpg",
            "http://www.stu.ru/images/theme/29772.jpg",
            "http://www.stu.ru/images/theme/29774.jpg",
            "http://www.stu.ru/images/theme/29776.jpg",
            "http://www.stu.ru/images/theme/29778.jpg",
            "http://www.stu.ru/images/theme/29780.jpg",
            "http://www.stu.ru/images/theme/29782.jpg",
            "http://www.stu.ru/images/theme/29784.jpg",
            "http://www.stu.ru/images/theme/29786.jpg",
            "http://www.stu.ru/images/theme/29788.jpg",
            "http://www.stu.ru/images/theme/29790.jpg",
            "http://www.stu.ru/images/theme/29792.jpg",
            "http://www.stu.ru/images/theme/29794.jpg",
            "http://www.stu.ru/images/theme/29796.jpg",
            "http://www.stu.ru/images/theme/29798.jpg",
            "http://www.stu.ru/images/theme/29800.jpg",
            "http://www.stu.ru/images/theme/29802.jpg",

            "http://www.stu.ru/images/theme/29565.jpg",
            "http://www.stu.ru/images/theme/29567.jpg",
            "http://www.stu.ru/images/theme/29569.jpg",
            "http://www.stu.ru/images/theme/29571.jpg",
            "http://www.stu.ru/images/theme/29573.jpg",
            "http://www.stu.ru/images/theme/29575.jpg",
            "http://www.stu.ru/images/theme/29577.jpg",
            "http://www.stu.ru/images/theme/29579.jpg",
            "http://www.stu.ru/images/theme/29581.jpg",
            "http://www.stu.ru/images/theme/29583.jpg",
            "http://www.stu.ru/images/theme/29585.jpg",

    };
}
